# Generated by Django 6.0.2 on 2026-02-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Minha Empresa', max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(default='00.000.000/0000-00', max_length=20, verbose_name='CNPJ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
    ]
