# Generated by Django 6.0.2 on 2026-02-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Logo da Empresa'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='state_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site / Instagram'),
        ),
    ]
