# Generated by Django 6.0.3 on 2026-03-24 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_paymentmethod_companysettings_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ex: Conta de Luz Março', max_length=200, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('fixed', 'Despesa Fixa (Água, Luz, Aluguel)'), ('purchase', 'Compra de Mercadoria/Estoque'), ('personnel', 'Pessoal / Salários'), ('marketing', 'Marketing / Anúncios'), ('taxes', 'Impostos / Taxas'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('paid', models.BooleanField(default=True, verbose_name='Pago?')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
