# Generated by Django 6.0.3 on 2026-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='background_color',
            field=models.CharField(default='#f4f6f9', max_length=20, verbose_name='Cor de Fundo'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='font_family',
            field=models.CharField(default='Poppins', max_length=50, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='font_size',
            field=models.IntegerField(default=14, verbose_name='Tamanho da Fonte (px)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color',
            field=models.CharField(default='#3498db', max_length=20, verbose_name='Cor Principal'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_color',
            field=models.CharField(default='#2c3e50', max_length=20, verbose_name='Cor Secundária'),
        ),
    ]
