# Generated by Django 6.0.2 on 2026-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Família Olfativa')),
            ],
            options={
                'verbose_name': 'Família Olfativa',
                'verbose_name_plural': 'Famílias Olfativas',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('favorite_brands', models.TextField(blank=True, help_text='Ex: Chanel, Dior (separado por vírgula)', verbose_name='Marcas Favoritas')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Pontos de Fidelidade')),
                ('classification', models.CharField(choices=[('novo', 'Novo'), ('recorrente', 'Recorrente'), ('vip', 'VIP')], default='novo', max_length=20, verbose_name='Classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragrance_preferences', models.ManyToManyField(blank=True, to='customers.fragrancefamily', verbose_name='Preferências Olfativas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
