# Generated by Django 6.0.2 on 2026-02-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_customer_address_customer_city_and_more'),
        ('products', '0002_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit', 'Cartão de Crédito'), ('debit', 'Cartão de Débito'), ('cash', 'Dinheiro')], default='pix', max_length=20, verbose_name='Pagamento')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Finalizada?')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Qtd')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Unit.')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
