# Generated by Django 6.0.2 on 2026-02-07 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Comissão'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'R$'), ('percent', '%')], default='fixed', max_length=10, verbose_name='Tipo Desconto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='installments',
            field=models.IntegerField(default=1, verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Finalizada'), ('canceled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_type',
            field=models.CharField(choices=[('fixed', 'R$'), ('percent', '%')], default='fixed', max_length=10, verbose_name='Tipo Acréscimo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acréscimo'),
        ),
    ]
