# Generated by Django 6.0.2 on 2026-02-07 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='OlfactoryFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Família Olfativa')),
            ],
            options={
                'verbose_name': 'Família Olfativa',
                'verbose_name_plural': 'Famílias Olfativas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('line', models.CharField(blank=True, help_text='Ex: Malbec, Acqua di Gio', max_length=100, verbose_name='Linha')),
                ('product_type', models.CharField(choices=[('perfume', 'Perfume (Frasco)'), ('decant', 'Decant (Amostra)'), ('kit', 'Kit / Combo'), ('cosmetic', 'Cosmético')], default='perfume', max_length=20, verbose_name='Tipo')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('U', 'Unissex')], default='U', max_length=1, verbose_name='Gênero')),
                ('top_notes', models.TextField(blank=True, verbose_name='Notas de Saída')),
                ('heart_notes', models.TextField(blank=True, verbose_name='Notas de Corpo')),
                ('base_notes', models.TextField(blank=True, verbose_name='Notas de Fundo')),
                ('volume', models.CharField(help_text='Ex: 100ml, 50ml, 5ml', max_length=50, verbose_name='Volume')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras')),
                ('batch_code', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Qtd. em Estoque')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='Marca')),
                ('olfactory_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.olfactoryfamily', verbose_name='Família Olfativa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
