# Generated by Django 6.0.2 on 2026-02-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cole um link de imagem da internet (opcional)', max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
    ]
