# Generated by Django 6.0.2 on 2026-02-12 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_supplier_product_category_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade no Kit')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_kits', to='products.product', verbose_name='Produto Componente')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product', verbose_name='Kit Pai')),
            ],
            options={
                'unique_together': {('kit', 'component')},
            },
        ),
    ]
