# Generated by Django 6.0.3 on 2026-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='entry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha apenas para recalcular o preço médio na entrada.', max_digits=10, null=True, verbose_name='Custo de Entrada (Unitário)'),
        ),
    ]
